# Generated by Django 3.2 on 2022-08-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_orderlineitem_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_bag',
            field=models.TextField(blank='False', default='', null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(blank='False', default='', max_length=254, null='False'),
            preserve_default='False',
        ),
    ]
